### ISSUE TITLE
Create new tag with fixes from MR #4 and #5

### ISSUE THREAD

**Issue by cholmcc** [alisw/thepeg#6]
Please create new tag - say `v2.2.2-alice2` from `master` to include changes in MR #5 and #4.

`thepeg.sh` in `alidist` should then then updated to pull the newly created tag. 

 See also https://github.com/alisw/alidist/pull/5171.

**Comment by maireiphc** [comment]
New tag for ThePEG 2.2.2-alice2, done by Marco.
https://github.com/alisw/thepeg/releases/tag/v2.2.2-alice2
The update of the recipe is now required on alidist (https://github.com/alisw/alidist/pull/5201)

**Comment by maireiphc** [comment]
Closing here.
